name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: varnish
            bootstrap: curl -Ls https://packages.varnish-software.com/varnish/bootstrap-deb.sh | sudo bash
            packages: varnish varnish-dev
          - name: varnish-plus
            bootstrap: curl -s https://packagecloud.io/install/repositories/varnishplus/60-enterprise/script.deb.sh | sudo INSTALL= bash
            packages: varnish-plus varnish-plus-dev
            test_tags: -tags varnish_plus

    name: ci (${{ matrix.name }})

    steps:
      - uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Install Varnish
        run: |
          ${{ matrix.bootstrap }}
          sudo apt-get update
          sudo apt-get install -qq ${{ matrix.packages }}
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ${{ matrix.test_tags }} ./...

      - name: Doc
        run: go list ./... | xargs -I{} go doc {}
